export const menuData = [
  {
    id: 'hot-bev',
    title: 'Hot Beverages',
    icon: '☕',
    navLabel: '☕ Hot Drinks',
    items: [
      { name: 'Indian Tea / Lemon Tea', price: 80 },
      { name: 'Green Tea', price: 100 },
      { name: 'Hot Coffee / Black Coffee', price: 130 },
      { name: 'Hot Chocolate', price: 130 },
      { name: 'Hot Lemon Ginger Honey', price: 110 },
    ],
  },
  {
    id: 'bev',
    title: 'Beverages & Shakes',
    icon: '🥤',
    navLabel: '🥤 Beverages',
    items: [
      { name: 'Mineral Water', price: 20 },
      { name: 'Cold Drinks', price: 70 },
      { name: 'Lemon Soda', price: 100 },
      { name: 'Nimbu Pani', price: 60 },
      { name: 'Butter Milk', price: 80 },
      { name: 'Cold Coffee', price: 170 },
      { name: 'Cold Coffee Choco Ice Cream', price: 210 },
      { name: 'Lassi', sub: 'Sweet / Salted', price: 120 },
      { name: 'Lassi', sub: 'Banana / Lemon / Honey', price: 170 },
      { name: 'Virgin Mojito', price: 180 },
      { name: 'Orange Mojito', price: 180 },
      { name: 'Shake', sub: 'Banana / Honey', price: 180 },
      { name: 'Oreo Shake', price: 210 },
    ],
  },
  {
    id: 'starters',
    title: 'Starters',
    icon: '🍟',
    navLabel: '🍟 Starters',
    items: [
      { name: 'Roasted Papad', price: 50 },
      { name: 'Masala Papad', price: 90 },
      { name: 'Salted Peanuts', price: 120 },
      { name: 'Peanut Masala', price: 120 },
      { name: 'French Fry', price: 180 },
      { name: 'Cheesy Fries', price: 230 },
      { name: 'Peri Peri French Fry', price: 230 },
      { name: 'Peri Peri Cheesy French Fry', price: 260 },
      { name: 'Veg Pakora', price: 210 },
      { name: 'Paneer Pakora', price: 260 },
    ],
  },
  {
    id: 'bread',
    title: 'Bread & Sandwich',
    icon: '🥪',
    navLabel: '🥪 Bread',
    items: [
      { name: 'Toast', sub: 'Butter / Jam / Honey', price: 80 },
      { name: 'Veg Sandwich', price: 130 },
      { name: 'Cheese Sandwich', price: 180 },
      { name: 'Veg Cheese Sandwich', price: 180 },
    ],
  },
  {
    id: 'breakfast',
    title: 'Indian Breakfast',
    icon: '🍽️',
    navLabel: '🍽️ Breakfast',
    items: [
      { name: 'Poha', price: 130 },
      { name: 'Upma', price: 160 },
      { type: 'subheading', label: '🫓 Paratha with Curd and Pickle' },
      { name: 'Plain Paratha', price: 120 },
      { name: 'Paratha', sub: 'Aalo / Onion / Mix Veg', price: 160 },
      { name: 'Paratha Gobi', price: 160 },
      { name: 'Paratha', sub: 'Cheese / Paneer', price: 180 },
      { name: 'Paratha Cheese Garlic', price: 180 },
    ],
  },
  {
    id: 'maggi',
    title: 'Maggi',
    icon: '🍜',
    navLabel: '🍜 Maggi',
    items: [
      { name: 'Maggi Masala', price: 160 },
      { name: 'Maggi Masala Cheese', price: 210 },
      { name: 'Maggi Vegetable', price: 180 },
      { name: 'Maggi Vegetable Cheese', price: 230 },
    ],
  },
  {
    id: 'egg',
    title: 'Egg',
    icon: '🍳',
    navLabel: '🍳 Egg',
    items: [
      { name: 'Boiled Egg', sub: 'One', price: 80 },
      { name: 'Plain Omelette', price: 120 },
      { name: 'Plain Cheese Omelette', price: 120 },
      { name: 'Veg Masala Omelette', price: 180 },
      { name: 'Veg Cheese Omelette', price: 210 },
    ],
  },
  {
    id: 'pizza',
    title: 'Pizza',
    icon: '🍕',
    navLabel: '🍕 Pizza',
    items: [
      { name: 'Garlic Bread', price: 180 },
      { name: 'Margarita Pizza', price: 250 },
      { name: 'Farmhouse Pizza', price: 300 },
      { name: 'Exotic Pizza', price: 350 },
      { name: 'Veg Supreme Pizza', price: 350 },
    ],
  },
  {
    id: 'pancake',
    title: 'Pancake (Egg)',
    icon: '🥞',
    navLabel: '🥞 Pancake',
    items: [
      { name: 'Pancake', price: 80 },
      { name: 'Pancake Honey', price: 130 },
      { name: 'Pancake Honey Banana', price: 180 },
      { name: 'Pancake Nutella', price: 220 },
      { name: 'Pancake Nutella Banana', price: 260 },
    ],
  },
]
